### PR TITLE
regEn: allow enable to depend on output

### LINKED ISSUE #104: `regEn#` fails to converge in sim when enable depends on previous output
In ed616b5, the (simulation-time) definition of `regEn#` was changed to evaluate its signal operands more eagerly and avoid a space leak.  The implementation is now a recursive stream generator using a helper function:

```haskell
regEn# :: SClock clk -> a -> Signal' clk Bool -> Signal' clk a -> Signal' clk a
regEn# _ = go
  where
    go o (e :- es) as@(~(x :- xs)) =
      o `seqX` o :- (as `seq` if e then go x es xs else go o es xs)
```

Note the tilde in the definition of `go`.  This is a lazy pattern match, ensuring that execution can "pass" the equals sign and yield `o` (the register's current value) before deconstructing `x :- xs` (the stream of potential new values).  This subtle detail ensures that a register can yield its current value when the *new* values depend on the current value, as in

```haskell
counter f = let x = regEn 0 f (x + 1) in x
```

There is no tilde in the deconstruction of the enable stream `e :- es`.  As a result, enables are eagerly deconstructed before output is yielded.  If the enable signal depends on the output, evaluation cannot proceed.  (In my case, this manifested as tests failing with "thread blocked indefinitely in an STM transaction" just after upgrading to the v0.7.1 tools, which bring in prelude 0.11.1 and this change.)

Here is a trivial case that no longer works with prelude 0.11.1:

```haskell
-- Use regEn to re-implement register
badRegister i v =
  let x = regEn i en v
      en = const True <$> x
  in x
```

### PR DESCRIPTION
**Pull request by cbiffle**
This uses a lazy pattern to delay deconstruction of the enable signal
until after the current value has been yielded.

Fixes #104

### CODE REVIEW

File: src/CLaSH/Signal/Internal.hs [hunk 1]
```diff
@@ -269,7 +269,7 @@ register# _ i s = i :- s
 regEn# :: SClock clk -> a -> Signal' clk Bool -> Signal' clk a -> Signal' clk a
 regEn# _ = go
   where
-    go o (e :- es) as@(~(x :- xs)) =
+    go o ~(e :- es) as@(~(x :- xs)) =
```
Comment (christiaanb) [inline src/CLaSH/Signal/Internal.hs]: Can you add the same `@`+`seq` pattern for the enables, otherwise this definition might leak the stream constructors `:-` in the enable:

So:

```haskell
go o en@(e :- es) as@(~(x :- xs)) =
  o `seqX` o :- (en `seq` as `seq` if e then go x es xs else go o es xs)
```

Comment (cbiffle) [inline src/CLaSH/Signal/Internal.hs]: Hmmm.  I had convinced myself that this was not necessary, because the first thing the RHS of the outer `:-` does when reduced is test `e` with an `if` -- implying that both `e :- es` and `e` itself had been reduced to WHNF.  However, we are in subtle enough territory here that I defer to your judgment.

I feel like the pattern used in this function is getting awkward, I may also take a crack at simplifying it.

Comment (christiaanb) [inline src/CLaSH/Signal/Internal.hs]: Actually, you were right, I was wrong. Could you revert back to the original code and add a comment go `go` along the lines of:

"Because both the enable and in the value argument of the register can be used in a feedback loop, we need lazy pattern matching on both those arguments. That is, in order to evaluate the first output sample `o :- ...`, we don't need to know the shape of our inputs. However, the enable and value argument should be evaluated to WHNF as soon as the tail of the result is evaluated to WHNF, otherwise we have a space-leak. The value argument `as` therefor needs an explicit `seq`; on the other hand, because the tail of the output depends on the value of `e`, the enable argument does not need an explicit `seq`."

Comment (cbiffle) [inline src/CLaSH/Signal/Internal.hs]: Done.

**Comment by christiaanb** [comment]
Thanks!
